name: MySQL on Alpine Without Service

on: [push, workflow_dispatch]

jobs:
  test-mysql:
    runs-on: ubuntu-latest

    container:
      image: alpine:latest

    steps:
      - name: Update and Install MySQL
        run: |
          apk update
          apk add --no-cache mysql mysql-client mysql-server
      
      - name: Initialize MySQL Database
        run: |
          mkdir -p /run/mysqld
          chown -R mysql:mysql /run/mysqld
          mysql_install_db --user=mysql --datadir=/var/lib/mysql

      - name: Start MySQL Service
        run: |
          mysqld --user=mysql --datadir=/var/lib/mysql --skip-networking=0 --socket=/run/mysqld/mysqld.sock & 
          sleep 10 # Wait for MySQL to start

      - name: Set Up MySQL User and Database
        run: |
          mysqladmin -u root password 'root'
          mysql -u root -proot -e "CREATE DATABASE testdb;"
          mysql -u root -proot -e "CREATE USER 'testuser'@'%' IDENTIFIED BY 'testpass';"
          mysql -u root -proot -e "GRANT ALL PRIVILEGES ON testdb.* TO 'testuser'@'%'; FLUSH PRIVILEGES;"

      - name: Test MySQL Connection
        run: |
          mysql -u testuser -ptestpass -e "SHOW DATABASES;" testdb
