name: Upload and Download Artifacts

on:
  push:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create an Artifact
        run: |
          echo "This is a test file" > my-artifact.txt
          mkdir artifacts && mv my-artifact.txt artifacts/

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: artifacts/

  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: Download Artifact from GitHub
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: downloaded-artifacts/

      - name: Verify Downloaded Artifact
        run: ls -l downloaded-artifacts/
