name: Run with MySQL Container
on: 
  workflow_dispatch:

jobs:
  test-mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.4.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Query
        run: |
          ping -c 4 127.0.0.1
          find / -type s
          mysql  127.0.0.1:3306 -uroot -e "SHOW DATABASES;"
      
