name: MySQL with Ubuntu Test

on:
  workflow_dispatch:
  
jobs:
  test-mysql:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    container:
      image: ubuntu:latest
      options: --name ubuntu-container
    steps:
      - name: Install MySQL Client in Ubuntu Container
        run: |
          apt-get update
          apt-get install -y mysql-client

      - name: Wait for MySQL to be Ready
        run: |
          for i in {30..0}; do
            if mysql -h 172.17.0.1 -u testuser -ptestpassword -e 'SELECT 1;' &> /dev/null; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Test MySQL Connection from Ubuntu
        run: |
          mysql -h 172.17.0.1 -u testuser -ptestpassword -e "SHOW DATABASES;"

      - name: Run Sample Query from Ubuntu
        run: |
          mysql -h 172.17.0.1 -u testuser -ptestpassword -D testdb -e "
          CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100));
          INSERT INTO users (name) VALUES ('Alice'), ('Bob');
          SELECT * FROM users;"
